image: golang:1.8
stages:
  - test
  - build

before_script:
  - go get github.com/tools/godep
  - cp -r /builds/rodrigodealer /go/src/github.com/rodrigodealer/
  - cd /go/src/github.com/rodrigodealer/realtime

build:
  stage: build
  script:
    - godep restore
    - godep go build

test:
  stage: test
  script:
    - godep restore
    - godep go test -v -cover ./...
